version: '3'

services:

  wagtail:
    build:
      context: .
      args:
        PROJECT_NAME: my_project
    image: wagtail
    container_name: wagtail
    restart: unless-stopped
    environment:
      SQL_ENGINE: 'django.db.backends.postgresql_psycopg2'
      SQL_DATABASE: 'db_wagtail'
      SQL_USER: 'db_user'
      SQL_PASSWORD: 'db_password'
      SQL_HOST: 'db'
      SQL_PORT: '5432'
      DATABASE: 'postgres'
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:ro
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'db_wagtail'
      POSTGRES_USER: 'db_user'
      POSTGRES_PASSWORD: 'db_password'
    expose:
      - 5432
